/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.User;

import Business.FinancialAccount.FinanceAccount;
import Business.FinancialAccount.FinanceAccountDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hema
 */
public class ManageFinanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFinanceJPanel
     */
    JPanel container;
    UserAccount userAccount;
    FinanceAccountDirectory financeAccountDirectory;
    FinanceAccount financeAccount;
    public ManageFinanceJPanel(JPanel container, UserAccount userAccount, FinanceAccountDirectory financeAccountDirectory) {
        initComponents();
        this.container = container;
        this.financeAccountDirectory = financeAccountDirectory;
        this.userAccount = userAccount;
        populateContent();
    }

    private void populateContent() {
        for(FinanceAccount financeAccount1 : financeAccountDirectory.getFinanceAccountList()) {
            if(financeAccount1.getUsername().equals(userAccount.getUsername())) {
                financeAccount = financeAccount1;
                break;
            }
        }
        cardNumberJTextField.setText(financeAccount.getCardNo());
        cvvJTextField.setText(financeAccount.getCvv());
        expirationMonthJTextField.setText(String.valueOf(financeAccount.getExpirationMonth()));
        expirationYearJTextField.setText(String.valueOf(financeAccount.getExpirationYear()));
        balanceJLabel.setText(String.valueOf(financeAccount.getBalance()));
    }
    
    private void validateAndUpdate() {
        String cardNo = cardNumberJTextField.getText();
        for(int i = 0; i <cardNo.length();i++){
            char c = cardNo.charAt(i);
            if(c<48 || c>57){
                JOptionPane.showMessageDialog(null, "Card number field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        String cvv = cvvJTextField.getText();
        for(int i = 0; i <cvv.length();i++){
            char c = cvv.charAt(i);
            if(c<48 || c>57){
                JOptionPane.showMessageDialog(null, "Ccv number field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        String expM = expirationMonthJTextField.getText();
        for(int i = 0; i <expM.length();i++){
            char c = expM.charAt(i);
            if(c<48 || c>57){
                JOptionPane.showMessageDialog(null, "Expiration month field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        if(Integer.parseInt(expM) <= 12 || Integer.parseInt(expM) > 0){
             JOptionPane.showMessageDialog(null, "Expiration month field should contain between 1 to 12", "Mismatch", JOptionPane.WARNING_MESSAGE);
             return;
        }
            
        String expY = expirationYearJTextField.getText();
        for(int i = 0; i <expY.length();i++){
            char c = expY.charAt(i);
            if(c<48 || c>57){
                JOptionPane.showMessageDialog(null, "Expiration year field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        if(expY.length() > 4 || expY.length() < 4) {
            JOptionPane.showMessageDialog(null, "Expiration year should contain only 4 digits", "Mismatch", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
                financeAccount.setCardNo(cardNo);
                financeAccount.setCvv(cvv);
                financeAccount.setExpirationMonth(Integer.parseInt(expM));
                financeAccount.setExpirationYear(Integer.parseInt(expY));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        balanceJLabel = new javax.swing.JLabel();
        backJButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cardNumberJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cvvJTextField = new javax.swing.JTextField();
        expirationMonthJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        expirationYearJTextField = new javax.swing.JTextField();
        updateJButton = new javax.swing.JButton();

        jLabel1.setText("Card Number");

        jLabel2.setText("cvv");

        jLabel3.setText("Current Balance");

        backJButton5.setText("Back");
        backJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Financial Details");

        jLabel5.setText("Valid Thru");

        jLabel6.setText("/");

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cardNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvvJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(expirationMonthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expirationYearJTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton5)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(balanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(updateJButton)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cardNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cvvJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(expirationMonthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(expirationYearJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(balanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(updateJButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton5ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButton5ActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        validateAndUpdate();
    }//GEN-LAST:event_updateJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton5;
    private javax.swing.JLabel balanceJLabel;
    private javax.swing.JTextField cardNumberJTextField;
    private javax.swing.JTextField cvvJTextField;
    private javax.swing.JTextField expirationMonthJTextField;
    private javax.swing.JTextField expirationYearJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
