/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.User;

import Business.Advertiser.Ads;
import Business.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Organization.UserOrganization;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BiddingWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hema
 */
public class UserWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkArea
     */
    JPanel container;
    UserAccount userAccount;
    Organization organization;
    UserOrganization userOrganization;
    AdminOrganization adminOrganization;
    SupplierDirectory supplierDirectory;
    Enterprise enterprise;
    float currentBid;
    BiddingWorkRequest biddingWorkRequest1, biddingWorkRequest2;
    public UserWorkArea(JPanel container, UserAccount userAccount, Organization organization, SupplierDirectory supplierDirectory, Enterprise enterprise) {
        initComponents();
        this.userAccount = userAccount;
        this.container = container;
        this.organization = organization;
        this.userOrganization = (UserOrganization) organization;
        this.supplierDirectory = supplierDirectory;
        this.enterprise = enterprise;
        this.adminOrganization = (AdminOrganization) enterprise.getAdminOrganization();
        populateAds();
    }

    private void populateAds() {
        for(BiddingWorkRequest biddingWorkRequest : adminOrganization.getWorkQueue().getBiddingWorkRequests()) {
            if(biddingWorkRequest.getBidCategory().getAdSpace().equals("Landing Page Top")) {
                if(adLabelTop.getText().equals("")) {
                    biddingWorkRequest1 = biddingWorkRequest;
                    Ads ad = biddingWorkRequest.getAd();
                    adLabelTop.setText("Clickable Ad: " + String.valueOf(ad));
                    currentBid = biddingWorkRequest.getBidValue();
                }
                else if(biddingWorkRequest.getBidValue() > currentBid) {
                    adLabelTop.setText(biddingWorkRequest.getAd().getAdString());
                    biddingWorkRequest1 = biddingWorkRequest;
                }
            }
            if(biddingWorkRequest.getBidCategory().getAdSpace().equals("Landing Page Side")) {
                if(adLabelSide.getText().equals("")) {
                    biddingWorkRequest2 = biddingWorkRequest;
                    Ads ad = biddingWorkRequest.getAd();
                    adLabelSide.setText("Clickable Ad: " + String.valueOf(ad));
                    currentBid = biddingWorkRequest.getBidValue();
                }
                else if(biddingWorkRequest.getBidValue() > currentBid) {
                    adLabelSide.setText(biddingWorkRequest.getAd().getAdString());
                    biddingWorkRequest2 = biddingWorkRequest;
                }
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopJButton = new javax.swing.JButton();
        adLabelTop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        viewBalanceJButton = new javax.swing.JButton();
        viewHistoryJButton = new javax.swing.JButton();
        adLabelSide = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shopJButton.setText("Shop");
        shopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopJButtonActionPerformed(evt);
            }
        });
        add(shopJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 107, 95, -1));

        adLabelTop.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        adLabelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adLabelTopMouseClicked(evt);
            }
        });
        add(adLabelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 11, 300, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("User Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 79, -1, -1));

        viewBalanceJButton.setText("Manage Finance");
        viewBalanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBalanceJButtonActionPerformed(evt);
            }
        });
        add(viewBalanceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 189, -1, -1));

        viewHistoryJButton.setText("View History");
        viewHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryJButtonActionPerformed(evt);
            }
        });
        add(viewHistoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 148, 95, -1));

        adLabelSide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adLabelSideMouseClicked(evt);
            }
        });
        add(adLabelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 220, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void shopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopJButtonActionPerformed
        // TODO add your handling code here:
        UserShopJPanel userShopJPanel = new UserShopJPanel(container, userAccount, supplierDirectory, userOrganization, organization.getFinancialAccountDirectory(), adminOrganization, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("User Product", userShopJPanel);
        layout.next(container);
    }//GEN-LAST:event_shopJButtonActionPerformed

    private void viewHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryJButtonActionPerformed
        // TODO add your handling code here:
        UserViewHistoryJPanel userViewHistoryJPanel = new UserViewHistoryJPanel(container, userAccount, userOrganization);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("User History", userViewHistoryJPanel);
        layout.next(container);
    }//GEN-LAST:event_viewHistoryJButtonActionPerformed

    private void adLabelTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adLabelTopMouseClicked
        // TODO add your handling code here:
        biddingWorkRequest1.setPageHit(biddingWorkRequest1.getPageHit() + 1);
        AdProductsJPanel adProductsJPanel = new AdProductsJPanel(container, userAccount, biddingWorkRequest1, userOrganization.getMasterOrderCatalog(), organization.getFinancialAccountDirectory(), enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Ad Products", adProductsJPanel);
        layout.next(container);
    }//GEN-LAST:event_adLabelTopMouseClicked

    private void viewBalanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBalanceJButtonActionPerformed
        // TODO add your handling code here:
        ManageFinanceJPanel manageFinanceJPanel = new ManageFinanceJPanel(container, userAccount, organization.getFinancialAccountDirectory());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Finance", manageFinanceJPanel);
        layout.next(container);
    }//GEN-LAST:event_viewBalanceJButtonActionPerformed

    private void adLabelSideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adLabelSideMouseClicked
        // TODO add your handling code here:
        biddingWorkRequest2.setPageHit(biddingWorkRequest2.getPageHit() + 1);
        AdProductsJPanel adProductsJPanel = new AdProductsJPanel(container, userAccount, biddingWorkRequest2, userOrganization.getMasterOrderCatalog(), organization.getFinancialAccountDirectory(), enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Ad Products1", adProductsJPanel);
        layout.next(container);
    }//GEN-LAST:event_adLabelSideMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adLabelSide;
    private javax.swing.JLabel adLabelTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton shopJButton;
    private javax.swing.JButton viewBalanceJButton;
    private javax.swing.JButton viewHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
