/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Advertiser;

import Business.Advertiser.AdDirectory;
import Business.Enterprise;
import Business.Organization.AdvertiserOrganization;
import Business.Organization.Organization;
import Business.Role.AdvertiserRole;
import Business.UserAccount.UserAccount;
import Interface.User.ManageFinanceJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hema
 */
public class AdvertiserWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdvertiserWorkAreaJPanel
     */
    JPanel container;
    UserAccount userAccount;
    AdDirectory adDirectory;
    Enterprise enterprise;
    AdvertiserRole role;
    AdvertiserOrganization organization;
    public AdvertiserWorkAreaJPanel(JPanel container, UserAccount userAccount, Enterprise enterprise, Organization organization) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = (AdvertiserOrganization) organization;
        role = (AdvertiserRole) userAccount.getRole();
        adDirectory = role.getAdvertiser().getAdDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageAdsJButton = new javax.swing.JButton();
        userProfilesJButton = new javax.swing.JButton();
        manageBidsJButton = new javax.swing.JButton();
        manageFinanceJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Advertiser Work Area");

        manageAdsJButton.setText("Manage Ads");
        manageAdsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdsJButtonActionPerformed(evt);
            }
        });

        userProfilesJButton.setText("User Profiles");
        userProfilesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProfilesJButtonActionPerformed(evt);
            }
        });

        manageBidsJButton.setText("Manage Bids");
        manageBidsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBidsJButtonActionPerformed(evt);
            }
        });

        manageFinanceJButton.setText("Manage Finance");
        manageFinanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFinanceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userProfilesJButton)
                            .addComponent(manageAdsJButton)
                            .addComponent(manageBidsJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(manageFinanceJButton)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manageAdsJButton)
                .addGap(18, 18, 18)
                .addComponent(userProfilesJButton)
                .addGap(18, 18, 18)
                .addComponent(manageBidsJButton)
                .addGap(18, 18, 18)
                .addComponent(manageFinanceJButton)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdsJButtonActionPerformed
        // TODO add your handling code here:
        ManageAdsJPanel manageAdsJPanel = new ManageAdsJPanel(container, userAccount, adDirectory, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Ads", manageAdsJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageAdsJButtonActionPerformed

    private void userProfilesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProfilesJButtonActionPerformed
        // TODO add your handling code here:
        UserProfilesJPanel userProfilesJPanel = new UserProfilesJPanel(container, userAccount, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("User Profiles", userProfilesJPanel);
        layout.next(container);
    }//GEN-LAST:event_userProfilesJButtonActionPerformed

    private void manageBidsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBidsJButtonActionPerformed
        // TODO add your handling code here:
        ManageBiddingJPanel manageBiddingJPanel = new ManageBiddingJPanel(container, userAccount, adDirectory, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Bids", manageBiddingJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageBidsJButtonActionPerformed

    private void manageFinanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFinanceJButtonActionPerformed
        // TODO add your handling code here:
        ManageFinanceJPanel manageFinanceJPanel = new ManageFinanceJPanel(container, userAccount, organization.getFinancialAccountDirectory());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Finance2", manageFinanceJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageFinanceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAdsJButton;
    private javax.swing.JButton manageBidsJButton;
    private javax.swing.JButton manageFinanceJButton;
    private javax.swing.JButton userProfilesJButton;
    // End of variables declaration//GEN-END:variables
}
