/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Advertiser;

import Business.Advertiser.AdDirectory;
import Business.Advertiser.Ads;
import Business.Enterprise;
import Business.Supplier.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hema
 */
public class ManageAdsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdsJPanel
     */
    JPanel container;
    AdDirectory adDirectory;
    UserAccount userAccount;
    Enterprise enterprise;
    public ManageAdsJPanel(JPanel container, UserAccount userAccount, AdDirectory adDirectory, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.adDirectory = adDirectory;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        System.out.println();
        populateAdsTable();
    }
    
    private void populateAdsTable() {
        DefaultTableModel model = (DefaultTableModel) adsJTable.getModel();
        model.setRowCount(0);
        for(Ads ads : adDirectory.getAdList()) {
            Object[] row = new Object[3];
            row[0] = ads;
            row[1] = ads.getProduct().getProductDescription();
            row[2] = ads.getProduct().getProductCategory();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adsJTable = new javax.swing.JTable();
        viewAndUpdateJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        createAdJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        adsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Ad Description", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adsJTable);

        viewAndUpdateJButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        viewAndUpdateJButton.setText("Remove Ad");
        viewAndUpdateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAndUpdateJButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Ads");

        createAdJButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createAdJButton.setText("Create Ad");
        createAdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshJButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(createAdJButton)
                                    .addGap(35, 35, 35)
                                    .addComponent(viewAndUpdateJButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refreshJButton))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAndUpdateJButton)
                    .addComponent(createAdJButton))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createAdJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdJButtonActionPerformed
        // TODO add your handling code here:
        CreateAdJPanel createAdJPanel = new CreateAdJPanel(container, userAccount,adDirectory, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Create Ads", createAdJPanel);
        layout.next(container);
    }//GEN-LAST:event_createAdJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateAdsTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void viewAndUpdateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAndUpdateJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = adsJTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Invalid Option", JOptionPane.WARNING_MESSAGE);
        }
        int option = JOptionPane.showConfirmDialog(null, "Are you sure", "Delete Product", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.NO_OPTION){
            return;
        }
        Ads ads = (Ads) adsJTable.getValueAt(selectedRow, 0);
        adDirectory.deleteAd(ads);
        populateAdsTable();
    }//GEN-LAST:event_viewAndUpdateJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adsJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createAdJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton viewAndUpdateJButton;
    // End of variables declaration//GEN-END:variables
}
