/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Supplier;


import Business.Enterprise;
import Business.Network.Network;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.ProductCategory.ProductCategory;
import Business.Supplier.Product;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hema
 */
public class CreateProductJPanel extends javax.swing.JPanel {
    /**
     * Creates new form CreateProductJPanel
     */
    private SupplierDirectory supplierDirectory;
    private JPanel container;
    private Supplier supplier;
    private Boolean flag;
    private Enterprise enterprise;
    AdminOrganization adminOrganization;
    String picture, link;
    public CreateProductJPanel(JPanel container, Supplier supplier, SupplierDirectory supplierDirectory, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.supplierDirectory = supplierDirectory;
        this.supplier = supplier;
        this.adminOrganization = (AdminOrganization) enterprise.getAdminOrganization();
        flag = true;
        populateProductCategory();
    }

    private void populateProductCategory() {
        productCategoryJComboBox.removeAllItems();
        for(ProductCategory productCategory : adminOrganization.getProductCategoryDirectory().getProductList())
            productCategoryJComboBox.addItem(productCategory.getCategory());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        productNameJTextField = new javax.swing.JTextField();
        productIdJTextField = new javax.swing.JTextField();
        productPriceJTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        descriptionJTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        imageJLabel = new javax.swing.JLabel();
        addImageJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        productCategoryJComboBox = new javax.swing.JComboBox();
        backJButton5 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Create a Product");

        jLabel2.setText("Product Name");

        jLabel3.setText("Product ID");

        jLabel4.setText("Product Price");

        createJButton.setText("Create Product");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Description");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        addImageJButton.setText("Add Image");
        addImageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(addImageJButton)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(addImageJButton)
                .addContainerGap())
        );

        jLabel7.setText("Product Category");

        backJButton5.setText("Back");
        backJButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton5)
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(productIdJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(productPriceJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(productNameJTextField)
                                .addComponent(descriptionJTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(productCategoryJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(createJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(backJButton5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(productCategoryJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productPriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(56, 56, 56)
                        .addComponent(createJButton)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void validate() {
        try {
                if(productNameJTextField.getText().equals("") || descriptionJTextField.getText().equals("") || productPriceJTextField.getText().equals("") || productIdJTextField.getText().equals("") || link == null) {
                JOptionPane.showMessageDialog(null, "Fill in all the fields", "Empty Text", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String id = productIdJTextField.getText();
            for(int i = 0; i <id.length();i++){
                char c = id.charAt(i);
                if(c<48 || c>57){
                    JOptionPane.showMessageDialog(null, "Product ID field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            String price = productPriceJTextField.getText();
            for(int i = 0; i <price.length();i++){
                char c = price.charAt(i);
                if(c<48 || c>57){
                     if(c !=46) {
                    JOptionPane.showMessageDialog(null, "Base Price field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                }
            }
            if(productCategoryJComboBox.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Product category not available", "Unavailable", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
                            for(Product p : supplier.getProductDirectory().getProductList()){
                                if(p.getProductId() == Integer.parseInt(productIdJTextField.getText())) {
                                    JOptionPane.showMessageDialog(null, "Please select a new product ID", "Duplicate ID", JOptionPane.WARNING_MESSAGE);
                                    return ;
                                }
                            }
                  
            int selectedValue = JOptionPane.showConfirmDialog(null,"Are you sure you want to add to "+ productCategoryJComboBox.getSelectedItem() +"?","Warning!",JOptionPane.YES_NO_OPTION);
            if(selectedValue == JOptionPane.NO_OPTION){
                return;
            }
        }
        catch(HeadlessException | NumberFormatException e) {}
            if(flag) {
                createProduct();
            }
    }
    
    private void createProduct() {
        supplier.getProductDirectory().createAndAddProduct(productNameJTextField.getText(), Integer.parseInt(productIdJTextField.getText()), Float.parseFloat(productPriceJTextField.getText()), descriptionJTextField.getText(), supplier.getSupplierName(), link, (String) productCategoryJComboBox.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Product creation successful! ", "Success", JOptionPane.WARNING_MESSAGE);
        
    }
    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        validate();
        
    }//GEN-LAST:event_createJButtonActionPerformed

    private Image scaleImage(Image img, int width, int height) {
        BufferedImage scaledImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = scaledImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, width, height, null);
        g2.dispose();
        return scaledImage;
    }
    
    private String picture() {
        try{
            JFileChooser chooser = new JFileChooser(".");
            int status = chooser.showOpenDialog(CreateProductJPanel.this);
            if(status == JFileChooser.APPROVE_OPTION){
                File file = chooser.getSelectedFile();
                if(file != null)
                    picture = file.getAbsolutePath();
            }
            
            Image image = new ImageIcon(picture).getImage();
            ImageIcon icon = new ImageIcon(scaleImage(image, imageJLabel.getWidth(), imageJLabel.getHeight()));
            imageJLabel.setIcon(icon);
            return picture;
        }
        catch(HeadlessException e) {}
        return null;
    }
    
    private void addImageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageJButtonActionPerformed
        // TODO add your handling code here:
        link = picture();
    }//GEN-LAST:event_addImageJButtonActionPerformed

    private void backJButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton5ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImageJButton;
    private javax.swing.JButton backJButton5;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField descriptionJTextField;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox productCategoryJComboBox;
    private javax.swing.JTextField productIdJTextField;
    private javax.swing.JTextField productNameJTextField;
    private javax.swing.JTextField productPriceJTextField;
    // End of variables declaration//GEN-END:variables
}
