/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Supplier;

import Business.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.Role.SupplierRole;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import Interface.User.ManageFinanceJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hema
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    private Enterprise enterprise;
    private UserAccount userAccount;
    private SupplierOrganization supplierOrganization;
    Organization organization;
    private JPanel container;
    SupplierRole role;
    Supplier supplier;
    public SupplierWorkAreaJPanel(JPanel container, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.organization = organization;
        this.supplierOrganization = (SupplierOrganization) organization;
        this.enterprise = enterprise;
        role = (SupplierRole) userAccount.getRole();
        supplier = role.getSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageProductJButton = new javax.swing.JButton();
        manageFinanceJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Supplier Work Area");

        manageProductJButton.setText("Manage Products");
        manageProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductJButtonActionPerformed(evt);
            }
        });

        manageFinanceJButton.setText("Manage Finance");
        manageFinanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFinanceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageFinanceJButton)
                            .addComponent(manageProductJButton))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(manageProductJButton)
                .addGap(27, 27, 27)
                .addComponent(manageFinanceJButton)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductJButtonActionPerformed
        // TODO add your handling code here:
        ManageProductCatalogJPanel manageProductCatalogJPanel = new ManageProductCatalogJPanel(container, supplier, supplierOrganization.getSupplierDirectory(), enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Product", manageProductCatalogJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageProductJButtonActionPerformed

    private void manageFinanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFinanceJButtonActionPerformed
        // TODO add your handling code here:
        ManageFinanceJPanel manageFinanceJPanel = new ManageFinanceJPanel(container, userAccount, organization.getFinancialAccountDirectory());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Finance1", manageFinanceJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageFinanceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageFinanceJButton;
    private javax.swing.JButton manageProductJButton;
    // End of variables declaration//GEN-END:variables
}
