/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.SystemAdmin;

import Business.Enterprise;
import Business.Organization.AdminOrganization;
import Business.UserAccount.UserAccount;
import Interface.User.ManageFinanceJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hema
 */
public class SystemAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    private Enterprise enterprise;
    private UserAccount userAccount;
    private JPanel container;
    public SystemAdminWorkArea(JPanel container, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageUserAccountsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageAuctionJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        manageCategoriesJButton = new javax.swing.JButton();
        manageFinanceJButton = new javax.swing.JButton();

        manageUserAccountsJButton.setText("Manage User Accounts");
        manageUserAccountsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountsJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("System Admin Work Area");

        manageAuctionJButton.setText("Manage Auction");
        manageAuctionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAuctionJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Network");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        manageCategoriesJButton.setText("Manage Categories");
        manageCategoriesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCategoriesJButtonActionPerformed(evt);
            }
        });

        manageFinanceJButton.setText("Manage Finance");
        manageFinanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFinanceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(manageUserAccountsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(manageOrganizationJButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageCategoriesJButton)
                            .addComponent(manageAuctionJButton)
                            .addComponent(manageFinanceJButton))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(manageOrganizationJButton)
                .addGap(18, 18, 18)
                .addComponent(manageUserAccountsJButton)
                .addGap(18, 18, 18)
                .addComponent(manageCategoriesJButton)
                .addGap(18, 18, 18)
                .addComponent(manageFinanceJButton)
                .addGap(18, 18, 18)
                .addComponent(manageAuctionJButton)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserAccountsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountsJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel manageUserAccountsJPanel = new ManageUserAccountsJPanel(container, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Accounts", manageUserAccountsJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageUserAccountsJButtonActionPerformed

    private void manageAuctionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAuctionJButtonActionPerformed
        // TODO add your handling code here:
        ManageAuctionJPanel manageAuctionJPanel = new ManageAuctionJPanel(container, userAccount, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Auction", manageAuctionJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageAuctionJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(container, enterprise.getNetworkDirectory());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Network", manageNetworkJPanel);
        layout.next(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(container, enterprise.getNetworkDirectory());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Organization", manageOrganizationJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageCategoriesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCategoriesJButtonActionPerformed
        // TODO add your handling code here:
        ManageCategoriesJPanel manageCategoriesJPanel = new ManageCategoriesJPanel(container, enterprise);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Categories", manageCategoriesJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageCategoriesJButtonActionPerformed

    private void manageFinanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFinanceJButtonActionPerformed
        // TODO add your handling code here:
        ManageFinanceJPanel manageFinanceJPanel = new ManageFinanceJPanel(container, userAccount, enterprise.getAdminOrganization().getFinancialAccountDirectory());
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("Manage Finance3", manageFinanceJPanel);
        layout.next(container);
    }//GEN-LAST:event_manageFinanceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAuctionJButton;
    private javax.swing.JButton manageCategoriesJButton;
    private javax.swing.JButton manageFinanceJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton manageUserAccountsJButton;
    // End of variables declaration//GEN-END:variables
}
